apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker-dr
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      protocols: all
      sslEnabled: false
    - expose: true
      name: amqp
      port: 5672
      protocols: amqp
      sslEnabled: false
      sslSecret: mytlssecret
  adminPassword: admin
  adminUser: admin
  brokerProperties:
    - maxDiskUsage=85
    - clusterConfigurations.my-cluster.producerWindowSize=-1
    - 'addressSettings.#.redeliveryMultiplier=5'
    - criticalAnalyzer=true
    - criticalAnalyzerTimeout=6000
    - criticalAnalyzerCheckPeriod=-1
    - criticalAnalyzerPolicy=LOG
    - AMQPConnections.prod.uri=tcp://ocp-machine-01.ak-ocp.aksa.com.pk:31626
    - AMQPConnections.prod.retryInterval=5000
    - AMQPConnections.prod.user=admin
    - AMQPConnections.prod.password=admin
    - AMQPConnections.prod.connectionElements.mirror.type=MIRROR
    - AMQPConnections.prod.connectionElements.mirror.messageAcknowledgements=true
    - AMQPConnections.prod.connectionElements.mirror.queueCreation=true
    - AMQPConnections.prod.connectionElements.mirror.queueRemoval=true
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: true
    managementRBACEnabled: true
    journalType: aio
    enableMetricsPlugin: true
    jolokiaAgentEnabled: true
    clustered: false
